language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt

script:
  - pytest

notifications:
  email:
    recipients:
      - kyle.pyprojects@gmail.com
    on_success: never
    on_failure: always